function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 17-Dec-2017 16:26:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YMinorGrid','on','XMinorGrid','on',...
    'YMinorTick','on',...
    'XMinorTick','on',...
    'Position',[0.152895336446412 0.0626165825275949 0.682352262052809 0.995037220843669]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 7]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'MarkerSize',4,'Marker','*');
set(plot1(1),'DisplayName','theorie','Color',[1 0 0]);
set(plot1(2),'DisplayName','pratique','Color',[0 1 0]);

% Create xlabel
xlabel('(Qv)^2','FontSize',11);

% Create ylabel
ylabel('F','FontSize',11);

% Create title
title('surface conique','FontSize',11);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

